services:
  bot:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - WORKSPACE=${WORKSPACE}
    command: sleep infinity
    networks:
      - default
    volumes:
      - ..:${WORKSPACE}:cached

networks:
  default:
