name: Develop

on:
  push:
    branches:
      - dev
      - develop
    paths:
      - "**/*.py"
      - ".github/workflows/develop.yml"
  pull_request:
    branches:
      - dev
      - develop
    paths:
      - "**/*.py"
      - ".github/workflows/develop.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        target:
          - "x86_64"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        uses: excitedleigh/setup-nox@v2.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - run: nox
